development:
  adapter: postgresql
  database: bitflower_1_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bitflower_1_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bitflower_1_prod
  pool: 5
  timeout: 5000